### ISSUE TITLE
Need to add/modify the Japanese document

### ISSUE THREAD

**Issue by taminta** [MicrosoftDocs/azure-docs.ja-jp#2921]
There is different information between English and Japanese.
Current English document has below information but Japanese document doesn't have it. This information is essential one so that it must be added.

https://docs.microsoft.com/en-us/azure/virtual-network/what-is-ip-address-168-63-129-16

"The following ports at least must be opened to allow communication with WireServer: 80, 443 and 3252"

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 2763b53f-2a31-cccf-8aaf-f082ebaeaad3
* Version Independent ID: 2cb6ee38-1d54-412f-a91c-a0e60000f3c9
* Content: [IP アドレス 168.63.129.16 とは](https://docs.microsoft.com/ja-jp/azure/virtual-network/what-is-ip-address-168-63-129-16)
* Content Source: [articles/virtual-network/what-is-ip-address-168-63-129-16.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/virtual-network/what-is-ip-address-168-63-129-16.md)
* Service: **virtual-network**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by srvbpigh** [comment]
Hello, @taminta
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @taminta
Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/virtual-network/what-is-ip-address-168-63-129-16

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team

**Comment by dcbrown16** [comment]
@CeciAc
The changes below are still not reflected several months after being updated in English. This seems longer than normal, is the change still in your backlog?
https://github.com/MicrosoftDocs/azure-docs/commit/2da6238be7e031768c2e3c992444f880d6f0f889#diff-fb0e87c79568fa6c696e97a300e317b5
