### ISSUE TITLE
Japanese error

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/azure-docs.ja-jp#513]
@dcbrown16 commented on [Tue Apr 24 2018](https://github.com/MicrosoftDocs/azure-docs/issues/7622)

Under "Configuration for deployment slots" there is a translation error.
Current: 接続設定 (スロット固有として構成可能)
Correct: 接続文字列 (スロット固有として構成可能)
(it says "connection settings" instead of "connection strings")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49f5ea0e-d951-7e7f-142e-3509b2ec5eda
* Version Independent ID: eea6bd7f-8790-caa0-aed8-bc0e79680bbd
* Content: [Set up staging environments for web apps in Azure App Service](https://docs.microsoft.com/en-us/azure/app-service/web-sites-staged-publishing)
* Content Source: [articles/app-service/web-sites-staged-publishing.md](https://github.com/Microsoft/azure-docs/blob/master/articles/app-service/web-sites-staged-publishing.md)
* Service: **app-service**
* GitHub Login: @cephalin
* Microsoft Alias: **cephalin**

---

@Sara-Nicolini commented on [Tue Apr 24 2018](https://github.com/MicrosoftDocs/azure-docs/issues/7622#issuecomment-384061438)

@BryanTrach-MSFT, pleaae assign loc issues to @DavidPrio

**Comment by CeciAc** [comment]
Hello, @dcbrown16
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/en-us/azure/app-service/web-sites-staged-publishing

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team

**Comment by dcbrown16** [comment]
@CeciAc oops, I spoke to soon. Took a quick look and this error is still present in one location under "デプロイ スロットの構成".

スワップされる設定:
一般設定 - フレームワーク バージョン、32/64 ビット、Web ソケットなど
アプリ設定 (スロット固有として構成可能)
接続**設定** (スロット固有として構成可能) < here
